autoreject/autoreject

autoreject/autoreject.py
=> cleaning up and reducing verbosity

autoreject/__init__.py, autoreject/autoreject.py, doc/api.rst, examples/plot_auto_repair.py
@raghavrv thanks for the suggestion.
=> MAINT: add LocalRejectCV for more optimized cross-val

autoreject/autoreject.py, autoreject/utils.py
cc @jona-sassenhagen let's see if this makes you happy. I think it should work with ipython notebooks. But I haven't tried yet. It should be drastically less verbose. It's another dependency but it's light and I think worth it.
I can add verbosity parameter too if you insist ;) But I might need more time to figure it out in that case ...
=> Less verbose progress reports

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py
closes https://github.com/autoreject/autoreject/issues/18
@jona-sassenhagen works for you?
=> FIX: sync with latest change in MNE for typechecking

.travis.yml, README.rst, autoreject/autoreject.py, circle.yml, doc/index.rst, examples/plot_auto_repair.py, examples/plot_ransac.py, examples/plot_visualize_bad_epochs.py
=> Remove dependency on pandas

autoreject/__init__.py, autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/tests/test_ransac.py, doc/api.rst, doc/index.rst, examples/plot_estimate_global_reject.py, examples/plot_global_reject.py
@agramfort does this do the job for you?
=> Function for rejection dictionary

autoreject/bayesopt.py
closes https://github.com/autoreject/autoreject/issues/35
@agramfort let me know if this "good enough" solution works for you
=> FIX suppress sklearn warnings

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/tests/test_ransac.py, autoreject/tests/test_utils.py, autoreject/tests/test_viz.py, autoreject/utils.py, autoreject/viz.py, examples/plot_channel_thresholds.py, examples/plot_visualize_bad_epochs.py
The goals of this PR are at least threefold:
1. enable ignoring channels, e.g. EOG
2. ignore channels previously marked as bad, consistent with MNE-Python behavior
3. prepare clean grouping by channel types
Don't merge it is not yet done  and does not work. 
cc @jasmainak
=> WIP: implement strict picking to support ignoring channels and clean grouping by type

autoreject/autoreject.py
closes https://github.com/autoreject/autoreject/issues/39
@craddm does this work for you?
=> Fix bug with mask

autoreject/autoreject.py, circle.yml, examples/plot_visualize_bad_epochs.py
closes https://github.com/autoreject/autoreject/issues/35
@ramonapariciog can you try this branch and see if it's any faster?
=> Make autoreject faster

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py, examples/plot_auto_repair.py
closes https://github.com/autoreject/autoreject/issues/37
@fraimondo do you have time to review. It seems related to your PR https://github.com/autoreject/autoreject/pull/24.
@ramonapariciog does this fix your problem?
=> Error -> warning for NO_DATA or TOO_SHORT

autoreject/autoreject.py, autoreject/bayesopt.py
=> Set random state for gaussian process regressor

autoreject/autoreject.py, autoreject/bayesopt.py, autoreject/tests/test_bayesopt.py, doc/conf.py
Taking over https://github.com/autoreject/autoreject/pull/57
=> [MRG] Caching issue

autoreject/autoreject.py, autoreject/ransac.py, autoreject/tests/test_autoreject.py, autoreject/tests/test_ransac.py, autoreject/tests/test_utils.py, autoreject/utils.py, examples/plot_auto_repair.py, examples/plot_channel_thresholds.py, examples/plot_ransac.py, examples/plot_visualize_bad_epochs.py
Yes, let's be pickier!
closes https://github.com/autoreject/autoreject/issues/33
=> ENH: Better picks

autoreject/autoreject.py, autoreject/bayesopt.py, autoreject/tests/test_bayesopt.py
closes https://github.com/autoreject/autoreject/issues/60
=> [MRG] Remove lbfgs_b

autoreject/autoreject.py, autoreject/bayesopt.py, autoreject/tests/test_autoreject.py, examples/plot_estimate_global_reject.py
closes https://github.com/autoreject/autoreject/issues/75.
=> [MRG] speedup get_rejection_thresholds

autoreject/autoreject.py
=> Remove ECG from global autoreject

circle.yml, doc/conf.py
This should hopefully fix circle ... fingers crossed
=> FIX circle

autoreject/utils.py
This is a minor bug, but I use the logger a lot.
=> Set log level back to where it was

autoreject/autoreject.py
=> FIX indexing bug in bad epochs for train

README.rst, autoreject/autoreject.py
closes https://github.com/autoreject/autoreject/issues/65
=> MRG: fix deprecation warnings for sklearn

autoreject/__init__.py, autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/tests/test_viz.py, autoreject/utils.py, autoreject/viz.py, doc/index.rst, examples/plot_auto_repair.py, examples/plot_visualize_bad_epochs.py
taking over https://github.com/autoreject/autoreject/pull/90/
still some issues to fix, but I think I got a handle on the changes done
=> [MRG + 1] rebase + API changes

autoreject/__init__.py, autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py, doc/api.rst, examples/plot_auto_repair.py, examples/plot_global_reject.py, examples/plot_visualize_bad_epochs.py
closes https://github.com/autoreject/autoreject/issues/100
=> [MRG] release pr

autoreject/__init__.py, doc/api.rst, doc/conf.py, doc/faq.rst, doc/index.rst
was just procrastinating a bit :)
=> [MRG] Add an FAQ section

.travis.yml
closes https://github.com/autoreject/autoreject/issues/106
procrastination break from packing ...
=> MAINT 3.6 python on travis

.travis.yml, autoreject/tests/test_utils.py, autoreject/utils.py, doc/conf.py, doc/whats_new.rst
=> [MRG] FIX bug in meg picks during interpolation

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py, autoreject/viz.py, doc/whats_new.rst
=> FIX check for channel locations

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py
=> [MRG] MAINT: check verbose arguments

doc/faq.rst
closes #118 
cc @dengemann @agramfort I saw this question twice today, so I had to make a PR :)
=> DOC: clarify why interpolation poses no harm

autoreject/autoreject.py, autoreject/utils.py
This does a much better job of displaying progress reports and not populating the entire screen when computing thresholds. Also removed a fix which was meant for older versions of MNE.
=> [MRG] Cleaner progress reports

autoreject/autoreject.py, doc/whats_new.rst, examples/plot_auto_repair.py, examples/plot_channel_thresholds.py, examples/plot_estimate_global_reject.py, examples/plot_global_reject.py, examples/plot_ransac.py
While going through the source, docs, and examples I noticed several places for improvement.
=> DOC: Several clarifications and syntax fixes

.circleci/config.yml, .gitignore, .travis.yml, README.rst, doc/conf.py, doc/index.rst
- trying to repair caching
- testing only on python 3.5 and higher
- adjusting docs
=> [MRG] Fix CIs

autoreject/ransac.py, doc/whats_new.rst
First attempt to fix the random sampling error when using Ransac with n_jobs > 1
=> Fix n_jobs > 1 error

autoreject/autoreject.py, autoreject/utils.py
=> FIX: use private function for extra param dots

doc/faq.rst
see: https://github.com/autoreject/autoreject/issues/111#issuecomment-527582092
cc @jasmainak
=> DOC: improve faq

.circleci/config.yml, .travis.yml, README.rst, autoreject/autoreject.py, autoreject/ransac.py, doc/index.rst
=> MAINT: use joblib instead of sklearn.joblib

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py
=> FIX: check for nan ch locs

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py, doc/whats_new.rst
=> Fixing pickling of AutoReject objects

autoreject/autoreject.py
This PR was discussed here.
https://github.com/autoreject/autoreject/issues/196
=> PR according to Issue

autoreject/utils.py, doc/whats_new.rst
=> DOC: add #212 to the Changelog

autoreject/ransac.py, autoreject/tests/test_ransac.py
=> fix: allow RandomState instance in Ransac

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py, doc/whats_new.rst
Thanks for the great package.
I have been using this small modification to use auto reject with my data. Are you interested in adding fNIRS support to this package? If so, I can expand this PR where necessary.
I will squash commits before asking for a merge.
=> MRG: Add fnirs support

autoreject/autoreject.py, doc/Makefile, examples/plot_autoreject_workflow.py
=> [MRG] DOC: start example for workflow

doc/faq.rst, examples/plot_autoreject_workflow.py, setup.py
=> [MRG] DOC: improve recommendation in FAQ

.circleci/config.yml, .github/workflows/circle-artifacts.yml, doc/Makefile, doc/whats_new.rst
follow up to #247 where I made a typo.
Also speeds everything up  :tada:
=> [MRG] fix/ci: use machine, not docker in CircleCI

.circleci/config.yml, doc/_templates/navbar.html
=> [MRG] ENH: dropdown

autoreject/autoreject.py, autoreject/tests/test_viz.py, doc/whats_new.rst
closes #241 
Thought this would be easy to support before the release.
=> [ENH] add ax param to RejectLog.plot method

autoreject/__init__.py, doc/whats_new.rst
=> start 0.4 dev cycle

autoreject/autoreject.py, setup.py
=> FIX modulenotfound error

.circleci/config.yml, .github/workflows/test.yml, LICENSE, README.rst, azure-pipelines.yml, doc/whats_new.rst, setup.py
=> DOC, INFRA, CI: document and bump versions

autoreject/__init__.py, autoreject/autoreject.py, autoreject/tests/test_autoreject.py, doc/api.rst, doc/whats_new.rst, examples/plot_autoreject_workflow.py
Taking over #270 started by @alexrockhill 
closes #269 
closes #271
=> [MRG] add reject_log option to ar.transform

autoreject/autoreject.py, autoreject/tests/test_autoreject.py, autoreject/utils.py, doc/whats_new.rst
fixes https://github.com/autoreject/autoreject/issues/276
=> get_rejection_threshold with augment=False

autoreject/tests/test_autoreject.py, autoreject/tests/test_ransac.py, autoreject/tests/test_utils.py, autoreject/tests/test_viz.py, examples/plot_auto_repair.py, examples/plot_channel_thresholds.py, examples/plot_estimate_global_reject.py, examples/plot_global_reject.py, examples/plot_ransac.py
Should fix https://dev.azure.com/autoreject/autoreject/_build/results?buildId=214&view=logs&j=c2fabf20-0dae-5771-2529-62cd5b113ff9&t=d66eb9f1-8d44-594c-8e02-393c3fa885da
=> MAINT: Use pathlib methods

autoreject/autoreject.py
Think this just corrects a typo.
=> Allow custom title to pass through plot function

.github/workflows/python-publish.yml, .github/workflows/test.yml, autoreject/autoreject.py, autoreject/ransac.py, doc/Makefile, doc/conf.py, doc/whats_new.rst, examples/plot_global_reject.py
=> use sphinxopts, fix docs

autoreject/autoreject.py
=> ENH: add option for aspect ratio

.github/workflows/test.yml, autoreject/__init__.py, autoreject/tests/test_autoreject.py, autoreject/tests/test_utils.py, autoreject/tests/test_viz.py, autoreject/utils.py
Should cut a 0.4.2 after this. Feel free to merge and release if you're happy @sappelhoff . I mostly just cherry-picked your commits :)
=> MAINT: Minor updates for latest MNE

autoreject/conftest.py
Should be backported once merged
=> MAINT: HDF5 deprecated use of NumPy prod

autoreject/autoreject.py, autoreject/tests/test_viz.py
=> MAINT: Dep

examples/plot_autoreject_workflow.py
based on a comment by a [user on the forum](https://mne.discourse.group/t/confusion-around-consensus-parameter-in-autoreject-and-ica/7392/4)
=> DOC FIX phrasing

examples/plot_autoreject_workflow.py
Fixes https://github.com/autoreject/autoreject/issues/319.
=> [ENH] Clarify language in example

autoreject/__init__.py, autoreject/autoreject.py, autoreject/ransac.py, autoreject/tests/test_autoreject.py, autoreject/tests/test_ransac.py, autoreject/tests/test_utils.py, autoreject/tests/test_viz.py, autoreject/utils.py, doc/whats_new.rst, setup.cfg
Closes #323
1. Replace `get_data()[:, picks]` with `get_data(picks)`
2. Add `copy=False` when relevant
=> MAINT: Update epochs.get_data calls

.git_archival.txt
=> remove ref-names from .git_archival.txt

.circleci/config.yml, .github/workflows/test.yml, README.rst, autoreject/conftest.py, doc/whats_new.rst, pyproject.toml
=> Bump Py version 3.10
