autoreject/autoreject.py

Analyse only the selected epochs drop_log, not all the entire drop_log.

Fix bug preveting fiting on epochs which were already cleaned

---

autoreject/autoreject.py
autoreject/ransac.py
autoreject/tests/test_autoreject.py
autoreject/utils.py
circle.yml
doc/index.rst
examples/plot_auto_repair.py
examples/plot_channel_thresholds.py
examples/plot_visualize_bad_epochs.py

[MRG] ENH/API: simplify / provide multi-channel fit

---

autoreject/autoreject.py
autoreject/tests/test_autoreject.py

@agramfort the problem was that with EOG channel, you do the cross validation with EEG or MEG data but the proposal thresholds have to come from EOG channel, not EEG or MEG

FIX global reject for EOG channel

---

autoreject/autoreject.py
autoreject/viz.py
examples/plot_channel_thresholds.py

@jbschiratti  reported to me that sometimes you just want to know the channel-level thresholds even if you don't have the channel locations: for example in the case of intracranial EEG data. Here is a small PR to add a boolean parameter `augment` to make data augmentation optional

Make data augmentation optional

---

autoreject/autoreject.py

Ignore good channels when there are more bad channels than n_interpolate by putting their values to minus infinite, like in the paper.
If this is not done explicitly, values of good channels can be lower because thresholds are different for each channel. This may lead to interpolate a lower number of channels than expected. So, they must be excluded, like in the reference paper.

Fix bug in selection of channels to interpolate

---

autoreject/autoreject.py

See issue #87.
Now the number of epochs rejected is directly corresponding to the number of epochs in which #bad_channels > consensus. Before 1 more epoch was rejected.

fixed number of epochs rejected

---

autoreject/autoreject.py
autoreject/tests/test_autoreject.py

Immediately end the interpolation crimes committed on master ...
More precisely, this PR ensures that the final list of to be interpolated channels matches the fix_log and the epochs in length. As of now, it could happen that arbitrary epochs get interpolated.
cc @agramfort @jasmainak

[BUG] crack down interpolation crime

---

autoreject/autoreject.py
autoreject/tests/test_autoreject.py
autoreject/tests/test_utils.py
autoreject/utils.py

This is the fix for the issue raised about transform interpolating bad channels back into the data.
I've added a test by comparing autoreject run on data with and without extra bad channels. However, I'm running into a bug that I don't quite understand while trying to pass this test. Autoreject on the copy of the data with bad channels fails on an assertion in line 273 of _interpolate_bads_meg_fast. This assertion seems to be asserting that the bad channels in the sub-selected info and the original info should be the same? I'm not sure why this would be the case. Am I misunderstanding or is this another bug?

WIP: Fix transform with bad channels.

---

autoreject/autoreject.py
autoreject/ransac.py
autoreject/utils.py
doc/whats_new.rst
examples/plot_visualize_bad_epochs.py

I profiled the code and it seemed to get some gains by changing how joblib does the hashing. I think if you try to hash the `info` object, it gets really slow. It seems to help cut around 30 seconds on the sample data example (!)
But there is a danger with using just the channel names for hashing as it could lead to potential collisions between datasets. One solution could be to use context managers to clean up the joblib directory every time `autoreject` runs ...

[MRG] autoreject is faster

---

autoreject/autoreject.py
autoreject/tests/test_autoreject.py
doc/whats_new.rst

closes #139
I have added a param ch_types so you can save time if you don't want rejection threshold for all channel types. Okay for you @agramfort @dengemann ? I find it useful as sometimes I don't want to reject based on EOG (e.g., for ICA), so I end up popping it from the dictionary in the end. But it wastes computation.

[MRG] FIX ch_type can be chosen

---

autoreject/autoreject.py

autoreject almost makes me feel *bad* for not having bad data:
```
"No bad epochs were found for your data. Returning "
"a copy of the data you wanted to clean. Interpolation "
"may have been done."
```
This makes that message conditional on verbose being != False.

Make transform respect verbose

---

.travis.yml
doc/conf.py
doc/explanation.rst
doc/faq.rst
examples/README.txt

closes #144 
Based on our discussion in #144 I try to put the "intuition" on autoreject global into a new section of the docs.
I think that this `explanations` section can grow over time and that it is a bit like the last "missing" part, when considering this [seminal pycon australia talk](https://www.divio.com/blog/documentation/) (link leads to associated blogpost)
I see:
- "learning oriented" covered by /examples
- "Problem oriented" covered by FAQ
- "understanding oriented" covered through this PR
- "information oriented" covered by the API
Note: The actual text in `explanation.rst` is still WIP, but I wanted your input on the structure before continuing to work on it.

[MRG] Extend documentation

---

setup.py

The changes here will change how `autoreject` looks on pypi. Currently, we see the following (see on [pypi](https://pypi.org/project/autoreject/)):
With the changes, this will look as such:
... except for the "Homepage" link (for that, one would have to set a `URL` field, similar to `DOWNLOAD_URL`)
This will invite users to check out the different pages.

add project urls to setup.py

---

README.rst

Using the CircleCi build of autoreject, we can provide a link to the "latest" docs. Similar to how we do it with MNE-BIDS.
rendered: https://github.com/autoreject/autoreject/blob/f301ecc444db2d29435c71a4b91f31eeade3ef9d/README.rst

provide link to latest docs as built by circleci

---

autoreject/tests/test_utils.py

closes #160 
@agramfort the test will fail now because there were some changes made on the MNE end. Not sure if we should also update the interpolation code inside `autoreject` or not.

MRG MAINT: update test using _interpolate_bads_eeg to use origin

---

.gitignore
.travis.yml
Makefile
autoreject/tests/test_autoreject.py
autoreject/tests/test_bayesopt.py
autoreject/tests/test_ransac.py
autoreject/tests/test_utils.py
autoreject/tests/test_viz.py
setup.cfg

closes #163 
Dropping the nose module, because it is not actively maintained. Moving to pytest!
using a mixture of:
- nose2pytest
- global search+replace
- manual fiddling
I tried to be as minimal as possible.

Drop NOSE module in favor of PYTEST

---

.circleci/config.yml
README.rst
autoreject/utils.py
doc/api.rst
examples/plot_visualize_bad_epochs.py
setup.py

Addresses https://github.com/mne-tools/mne-python/issues/9078.
Instead of downloading a whole tar file that is stashed somewhere, the idea is to change to using `openneuro-py` to download example data files.

[ENH] Change to OpenNeuro-py downloader for example

---

autoreject/tests/test_utils.py
autoreject/utils.py
doc/whats_new.rst

see https://mne.discourse.group/t/using-autoreject-to-compute-local-threshes-impacts-the-epochs-dropped-using-a-global-threshold/2931
on mailing list

[MRG] FIX: don't reset bad channels

---

.github/workflows/test.yml
README.rst
autoreject/utils.py
doc/index.rst

Here is a start of a PR that ~addresses~ closes #211.
Note that this adjusts to behavior of MNE that will be released with MNE 0.24 if I am not mistaken.
~When I tested this locally, it seems that there are further adjustments needed, because MNE's ``_setup_dots`` does not return ``noise`` as a dictionary anymore, but as an ``mne.cov.Covariance`` object, and on a first, quick glance this seems to break some things.~ EDIT: Nevermind - I passed the wrong ``info`` :) . Thx @jasmainak for catching this!
[edit: removed erroneous tracebacks]
(Happy to look into this further, but need to rush to a meeting now - PRing this now to not delay anyone else)

MNT: Pass info as recently required positional argument

---

autoreject/autoreject.py
autoreject/ransac.py
autoreject/tests/test_ransac.py
autoreject/utils.py
doc/whats_new.rst

Fixes issue #224.
Use MNE `_picks_to_idx()` function to handle picks. Supports both strings and array of indices.
Added test for a string argument.
Is there a changelog to update? Anything else which I might add?

Fix #224 - Allow passing a valid string to picks.

---

autoreject/autoreject.py
examples/plot_autoreject_workflow.py

While giving a shot to the `AutoReject` class, I got confused by the docstring not matching the actual arguments. 
I changed the docstring to match the argument order.
TODO:

[DOC] fix argument order between n_interpolate and consensus

---

doc/conf.py
doc/whats_new.rst
setup.py

I think this would be a neat addition, similar to [gh_substitutions.py](https://github.com/mne-tools/mne-bids/blob/4c0755c6eb567c7840d70acf06f22201c5e75c65/doc/sphinxext/gh_substitutions.py#L1) in mne-bids, but without having to add an extra file.
Changelog was updated using regexps in VSCode search&replace:
- find:
```
`#(\d+) <https://github.com/autoreject/autoreject/pull/\d+>`_
```
- replace:
```
:github:`#$1`
```

doc: use sphinx-gihub-role package

---

.github/workflows/python-publish.yml

Still need to set `PYPI_USERNAME ` and `PYPI_PASSWORD` (it's an upload token, not a password), but for that I need more repo rights than I currently have.
To do:

add python publish workflow

---

autoreject/autoreject.py
autoreject/ransac.py
autoreject/utils.py
doc/_templates/autosummary/class.rst
doc/_templates/autosummary/function.rst
doc/conf.py

Apart from `__init__`, one cannot inspect methods for AutoReject in the docs: https://autoreject.github.io/dev/generated/autoreject.AutoReject.html#autoreject.AutoReject
trying to fix that here.

[MRG] DOC: show methods in API docs

---

autoreject/ransac.py
autoreject/tests/test_ransac.py
autoreject/utils.py
doc/whats_new.rst

closes #277 
closes #278 
The current implementation of RANSAC has some bugs renderering it faulty&non-functioning for `n_jobs>1`, and I'm not even sure if the case `n_jobs=1` is maybe also affected by this in certain cases.
I introduce and propose the following changes:
* Compute the mappings (interpolations of subsets of channels) with `Parallel`,  `_get_mappings` is actually the slow part of RANSAC and benefits of parallelization the most (at least for MEG data).
* Fix two bugs (list index taken instead of actual channel index, iterating over spaces of n_jobs instead of all epochs) see also #277 and #278 for details, additionally, the corresponding lines have been commented on in the review )
* The only part that needs randomization is `_get_random_subsets`, which does not need to be …

Fix and refactor RANSAC for n_jobs>1

---

autoreject/__init__.py
doc/_templates/navbar.html
doc/whats_new.rst

Bumping minor version from 0.3 to 0.4.
I considered a patch bump from 0.3.2 to 0.3.3 but it seemed like there was enough stuff (like ECoG/sEEG support) to justify a new minor bump.
Closes #288

MAINT: Bump in prep for release

---

autoreject/conftest.py
autoreject/ransac.py
autoreject/utils.py

In https://github.com/mne-tools/mne-python/pull/11903 we're trying to make some `mne/io` stuff private. This changes `autoreject` to use the explicitly public API

MAINT: Use explicitly public functions

---

autoreject/autoreject.py
autoreject/tests/test_autoreject.py
doc/whats_new.rst

I describe the issue being fixed here: https://github.com/autoreject/autoreject/issues/309#issuecomment-1689276690

Sort Autoreject.picks to avoid AssertionError
